routes/index.py
import json
from random import randint

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    flash, make_response,
)

from config import admin_mail
from models.message import send_mail
from models.session import ServerSession
from models.user import User
from routes import current_user
from routes.myredis import user_identify_cache

main = Blueprint('index', __name__)


@main.route('/')
def index():
    if current_user() is not None:
        return redirect(url_for('my_topic.index'))
    return render_template('index/index.html')


@main.route('/login_page')
def login_page():
    return render_template('index/index.html')


@main.route('/register')
def register():
    email = request.args.get('email', None)
    if email is None:
        return redirect('/')
    return render_template('index/register.html', email=email)


@main.route('/register/captcha', methods=['POST'])
# 发送包含注册验证码的邮件，跳转到输用户名，验证码，密码的界面
def register_check_mail():
    email = request.form.get('email', '')
    u = User.one(email=email)
    if u is None:
        verify_code = ''.join([str(randint(0, 9)) for _ in range(6)])
        user_identify_cache.set(email, verify_code, 600)
        title = '欢迎注册Swordman BBS'
        content = '欢迎注册Swordman BBS。您的验证码为{}，' \
                  '如果不是您本人的操作，请无视本邮件。'.format(verify_code)
        try:
            send_mail(
                subject=title,
                author=admin_mail,
                to=email,
                content=content, )
            flash('验证码已发送至您的邮箱，请查收。')
            return redirect(url_for('.register', email=email))

        except ValueError:
            flash('邮箱已被注册或邮箱格式错误')
            return redirect('/')
    else:
        flash('邮箱已被注册或邮箱格式错误')
        return redirect('/')


@main.route('/register', methods=['POST'])
def register_post():
    form = request.form.to_dict()
    verify_code = form.pop('verify_code', '')
    email = form.get('email', '')
    if user_identify_cache.exists(email) and int(user_identify_cache.get(email)) == int(verify_code):
        u = User.register(form)
        if u is not None:
            flash('用户{}注册成功，请登录'.format(u.username))
            user_identify_cache.delete(email)
            return redirect('/')
        else:
            return redirect(request.referrer)

    else:
        flash('无效的验证码，请重试')
        return redirect(request.referrer)


@main.route('/login', methods=['POST'])
def login_post():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        flash('用户名或密码错误')
        return redirect(url_for('index.index'))
    else:
        # 使用flask版本的客户端session:
        # session['user_id'] = u.id
        # # 设置 cookie 有效期为 永久
        # session.permanent = True
        # return redirect(url_for('gua_topic.index'))

        # 使用redis实现服务端session:
        response = make_response(redirect(url_for('my_topic.index')))
        user_session = ServerSession.new(u.id)
        response.headers['Set-Cookie'] = 'session_id=' + user_session.session_id
        key = 'session_id.{}'.format(user_session.session_id)
        user_identify_cache.set(key, json.dumps(user_session.todict()))

        return response


def not_found(e):
    return render_template('404.html')


@main.route('/logout')
def logout():
    session_id = request.cookies.get('session_id')
    key = 'session_id.{}'.format(session_id)
    if session_id is not None and user_identify_cache.exists(key):
        user_identify_cache.delete(key)
    return redirect('/')

routes/topic.py
import time

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    flash,
    abort,
)

from sqlalchemy import desc
from models.base_model import db
from models.board import Board
from routes import (current_user,
                    csrf_required,
                    new_csrf_token,
                    login_required,
                    inform_at,
                    topic_owner_required_post,
                    at_users,
                    cached_topic_id2topic,
                    )

from models.topic import Topic
from routes.myredis import (data_cache,
                            cached_replies_by_topic_id,
                            cached_user_id2user,
                            )

main = Blueprint('my_topic', __name__)


@main.app_template_filter()
def get_author(topic):
    """获取话题作者"""
    author_id = topic.user_id
    return cached_user_id2user(author_id)


@main.app_template_filter()
def content_with_clickable_name(content: str):
    """@功能"""
    for n in at_users(content):
        s = '@' + n.username
        content = content.replace(s, '<a href="/user/{}">@{}</a>'.format(n.id, n.username))
    return content


@main.route('/')
def index():
    """获取话题主页，每个话题cell 最后回复人的头像，
    最后变动时间，作者头像，评论数、浏览数。
    根据query选定板块"""
    visitor = current_user()
    board_id = int(request.args.get('board_id', -1))
    current_bid = board_id
    if board_id == -1:
        recent_active_topics = db.session.query(Topic).order_by(desc(Topic.last_active_time))
    else:
        recent_active_topics = db.session.query(Topic).filter_by(board_id=current_bid).order_by(
            desc(Topic.last_active_time))
    bs = Board.all()
    return render_template('topic/index.html',
                           recent_topics=recent_active_topics,
                           current_bid=current_bid,
                           user=visitor,
                           bs=bs,
                           )


@main.route('/<topic_id>')
def detail(topic_id):
    """
    id 为Topic 的话题的详情页
    """
    cur_topic = Topic.get(topic_id)
    if cur_topic is None:
        return abort(404)

    key = 'topic_id_{}.topic_info'.format(topic_id)
    # 每次有人点开详情页，需要更新浏览数，故旧缓存作废
    data_cache.delete(key)
    replies = cached_replies_by_topic_id(topic_id)
    board = Board.one(id=cur_topic.board_id)
    author = cached_user_id2user(cur_topic.user_id)
    token = new_csrf_token()
    return render_template('topic/detail.html',
                           topic=cur_topic,
                           replies=replies,
                           author=author,
                           token=token,
                           board=board,
                           visitor=current_user()
                           )


@main.route('', methods=['POST'])
@login_required
@csrf_required
def add():
    """
    执行新增Topic
    """
    form = request.form.to_dict()
    u = current_user()
    t = Topic.add(form, user_id=u.id)

    # 新增话题后，user_id 下所有话题的缓存失效，清理旧缓存。
    key = 'user_id_{}.created_topics'.format(u.id)
    data_cache.delete(key)

    inform_at(t, t.content, u)
    return redirect(url_for('.detail', topic_id=t.id))


@main.route("/posting")
@login_required
def new():
    """进入新建Topic的编辑页面"""
    current_bid = int(request.args.get('board_id', -1))
    token = new_csrf_token()
    u = current_user()
    bs = Board.all()
    return render_template("topic/new.html",
                           token=token,
                           user=u,
                           current_bid=current_bid,
                           bs=bs
                           )


@main.route("/deletion", methods=['POST'])
@topic_owner_required_post
@csrf_required
def delete():
    """删除某个话题，话题id从form中获取"""
    user_id = current_user().id
    i = int(request.form.get('topic_id', -1))
    topic = Topic.one(id=i)
    if topic is not None:
        # 删帖后，清理该帖子相关的缓存
        with data_cache.pipeline(transaction=False) as pipe:
            key = 'topic_id_{}.topic_info'.format(i)
            key2 = 'user_id_{}.created_topics'.format(user_id)
            key3 = 'topic_id_{}.replies'.format(topic.id)
            pipe.delete(key)
            pipe.delete(key2)
            pipe.delete(key3)

            delete_rep_id_list = Topic.delete(topic)
            for i in delete_rep_id_list:
                key = 'reply_id_{}.reply_info'.format(i)
                data_cache.delete(key)
            pipe.execute()

        flash('帖子删除成功')
    return redirect(url_for('my_user.user_created_topics', user_id=user_id))


@main.route("/<topic_id>/edit")
@login_required
def edit(topic_id):
    """进入话题编辑页面的get请求"""
    # old_topic: Topic = Topic.one(id=id)
    old_topic: Topic = cached_topic_id2topic(topic_id)
    token = new_csrf_token()
    u = current_user()
    all_borads = Board.all()

    if u.id != old_topic.user_id:
        return abort(404)

    return render_template("topic/edit.html",
                           token=token,
                           user=u,
                           current_bid=old_topic.board_id,
                           bs=all_borads,
                           old_topic=old_topic,
                           )


@main.route("/<int:id>/edit", methods=['POST'])
@login_required
@csrf_required
# 从编辑页面提交修改的post请求
def edit_post(id):
    form = request.form.to_dict()
    now = time.time()
    Topic.update(id, **form, last_edit_time=now, last_active_time=now)
    key = 'topic_id_{}.topic_info'.format(id)
    data_cache.delete(key)
    return redirect(url_for('.detail', topic_id=id))

routes/user.py
import os
import uuid

from flask import (render_template,
                   abort,
                   request,
                   flash,
                   redirect,
                   url_for,
                   send_from_directory,
                   Blueprint,
                   )

from werkzeug.datastructures import FileStorage

from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import (login_required,
                    current_user,
                    new_csrf_token,
                    csrf_required,
                    cached_topic_id2topic,
                    cached_user_id2user,
                    )
from routes.myredis import (cached_created_topics,
                            cached_replied_topics,
                            data_cache,
                            )

main = Blueprint('my_user', __name__)


@main.route('/profile')
@login_required
def profile():
    """用户的个人主页"""
    u = current_user()
    visitor_id = u.id
    recent_create_topics = Topic.newest_n(5, user_id=visitor_id)
    replies = Reply.newest_n(user_id=visitor_id)
    recent_rep_topics = []
    for rep in replies:
        topic = cached_topic_id2topic(rep.topic_id)
        if topic not in recent_rep_topics:
            recent_rep_topics.append(topic)
        if len(recent_rep_topics) >= 5:
            break

    return render_template('user/user_profile.html',
                           user=u,
                           recent_rep_topics=recent_rep_topics,
                           recent_create_topics=recent_create_topics,
                           visitor_id=visitor_id)


@main.route('/user/<user_id>')
def user_detail(user_id):
    """访问其他用户"""
    u = cached_user_id2user(user_id)
    visitor = current_user()
    if u is None:
        return abort(404)
    else:
        recent_create_topics = Topic.newest_n(5, user_id=user_id)
        replies = Reply.newest_n(user_id=user_id)
        recent_rep_topics = []
        for rep in replies:
            topic = cached_topic_id2topic(rep.topic_id)
            if topic not in recent_rep_topics:
                recent_rep_topics.append(topic)
            if len(recent_rep_topics) >= 5:
                break

        return render_template('user/user_profile.html',
                               user=u,
                               visitor=visitor,
                               recent_rep_topics=recent_rep_topics,
                               recent_create_topics=recent_create_topics,
                               )


@main.route('/user/<user_id>/topics/')
def user_created_topics(user_id):
    """查看用户发表的所有帖子"""
    u = cached_user_id2user(user_id)
    if u is None:
        abort(404)
    else:
        topics = cached_created_topics(user_id)
        topics.sort(key=lambda x: x.last_active_time, reverse=True)
        return render_template('user/user_items.html',
                               itemtype='创建',
                               topics=topics,
                               user=u,
                               )


@main.route('/user/<user_id>/replies/')
def user_replied_topics(user_id):
    """查看用户回复过的所有帖子"""
    u = cached_user_id2user(user_id)
    if u is None:
        abort(404)
    else:
        # replies = Reply.all(user_id=id)
        #
        # topics = []
        # if replies:
        #     for rep in replies:
        #         topic = Topic.one(id=rep.topic_id)
        #         if topic not in topics:
        #             topics.append(topic)
        #     topics.sort(key=lambda x: x.last_active_time, reverse=True)
        topics = cached_replied_topics(user_id)
        return render_template('user/user_items.html',
                               itemtype='参与',
                               topics=topics,
                               user=u,
                               )


@main.route('/setting')
@login_required
def setting():
    """设置页面"""
    u = current_user()
    token = new_csrf_token()
    return render_template('user/setting.html', user=u, token=token)


@main.route('/setting', methods=['POST'])
@login_required
@csrf_required
def setting_post():
    """提交更改"""
    u = current_user()
    form = request.form.to_dict()

    if form['action'] == 'change_password':  # 如果用户点击的是更改密码
        new_pass = form['new_pass']

        if u.password == User.salted_password(form['old_pass']):
            if len(new_pass) <= 2:
                flash('密码强度过低，请重新输入')
            else:
                User.update(u.id, password=User.salted_password(new_pass))
                key = 'user_id_{}.user_info'.format(u.id)
                data_cache.delete(key)
                flash('密码修改成功')
        else:
            flash('密码错误，请重新输入')

    elif form['action'] == 'change_settings':
        # 如果用户点击的是更改设置，修改同步到数据库，并清理redis失效缓存
        new_name = form['name']
        if new_name != u.username:  # 如果修改了用户名，需要检测新用户名是否被占用
            if User.one(username=new_name) is None:
                User.update(u.id, username=new_name, signature=form['signature'])
                key = 'user_id_{}.user_info'.format(u.id)
                data_cache.delete(key)
                flash('个人资料修改成功')
            else:
                flash('用户名被占用，请重新输入')
        else:  # 如果没修改用户名
            User.update(u.id, signature=form['signature'])
            key = 'user_id_{}.user_info'.format(u.id)
            data_cache.delete(key)
            flash('个人资料修改成功')

    return redirect(url_for('.setting'))


@main.route('/image/avatar', methods=['POST'])
@login_required
@csrf_required
def avatar_set():
    """设置头像"""
    u = current_user()
    file: FileStorage = request.files['avatar']
    filename = 'avatar_uid=[{}]'.format(u.id)+str(uuid.uuid4())
    path = os.path.join('images', filename)
    file.save(path)
    User.update(u.id, image='/images/{}'.format(filename))
    key = 'user_id_{}.user_info'.format(u.id)
    data_cache.delete(key)
    return redirect(url_for('.profile'))


@main.route('/images/<filename>')
def image(filename):
    return send_from_directory('images', filename)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Swordman BBS - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>

<body>
<!-- navbar -->
<div class='navbar'>

    <div class='navbar-inner'>
        <div class='container'>
            <a class='brand' href='/'>
                <img src="/images/Swordman">
            </a>
            <ul class='nav pull-right'>
                <li><a href='{{ url_for('my_topic.index') }}'>话题</a></li>
                {% set cur_user = current_user() %}
                {% if not cur_user %}
                    <li><a href='{{ url_for('index.login_page') }}'>注册</a></li>
                    <li><a href='{{ url_for('index.login_page') }}'>登录</a></li>
                {% else %}
                    <li>
                        <a href="/info" target="">
                            通知 <q style="color: #0e90d2">{{ unread_info_num_of_user(cur_user) }}</q>
                        </a>
                    </li>
                    <li><a href="/mail" target="">私信<q
                            style="color: #0e90d2">{{ unread_message_num_of_user(cur_user) }}</q></a>
                    </li>
                    <li><a href="/setting" target="">设置</a></li>
                    <li><a href='{{ url_for('my_user.profile') }}'>{{ cur_user.username }}</a></li>
                    <li><a href='{{ url_for('index.logout') }}'>注销</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
<div id="main">
    <!-- sidebar -->
    <div id="sidebar">
        <div class="panel">

            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="/user/{{ user.id }}">
                            <img alt="用户头像" src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name"><a class="dark"
                                                   href="/user/{{ user.id }}">{{ user.username }}</a></span>

                        <div class="space clearfix"></div>
                        <span class="signature">
        {{ user.signature }}
    </span>

                    </div>
                </div>
            </div>
        </div>


        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('my_topic.new') }}" id="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">友情链接</span>
            </div>
            <div class="inner">
                <ol class="friendship-community">
                    <li>
                        <a href="https://www.python.org/" target="_blank">
                            <img src="/images/python-logo.png">
                        </a>
                    </li>
                    <div class="sep10"></div>
                </ol>
            </div>
        </div>


        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>本站作者</span>
            </div>
            <div class='inner cnode-app-download'>
                <img width='200' src="/images/my_weixin.png">
                <br>
                扫一扫添加Swordman
                <br>
                <a href="https://github.com/imjerry1994/web_bbs">本站源码</a>
            </div>
        </div>
    </div>

    {% block main %}
    {% endblock %}
</div>

<script>
    // 当网页向下滑动 20px 出现"返回顶部" 按钮
    window.onscroll = function () {
        scrollFunction()
    };

    function scrollFunction() {
        console.log(121);
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            document.getElementById("btnTop").style.display = "block";
        } else {
            document.getElementById("btnTop").style.display = "none";
        }
    }

    // 点击按钮，返回顶部
    function returnTop() {
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }
</script>
<div>
    <button onclick="returnTop()" id="btnTop" title="返回顶部">返回顶部</button>
</div>
</body>
</html>

templates/base_nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Swordman BBS - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
</head>

<body>
<!-- navbar -->
<div class='navbar'>
    <div class='navbar-inner'>
        <div class='container'>
            <a class='brand' href='/'>
                <img src="/images/Swordman">
            </a>
            <ul class='nav pull-right'>
                <li><a href='{{ url_for('my_topic.index') }}'>话题</a></li>
                {% set cur_user = current_user() %}

                {% if not cur_user %}
                    <li><a href='{{ url_for('index.login_page') }}'>注册</a></li>
                    <li><a href='{{ url_for('index.login_page') }}'>登录</a></li>
                {% else %}
                    <li>
                        <a href="/info" target="">
                            通知 <q style="color: #0e90d2">{{ unread_info_num_of_user(cur_user) }}</q>
                        </a>
                    </li>
                    <li><a href="/mail" target="">私信<q
                            style="color: #0e90d2">{{ unread_message_num_of_user(cur_user) }}</q></a>
                    </li>
                    <li><a href="/setting" target="">设置</a></li>
                    <li><a href='{{ url_for('my_user.profile') }}'>{{ cur_user.username }}</a></li>
                    <li><a href='{{ url_for('index.logout') }}'>注销</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
<div id="main">
    {% block main %}
    {% endblock %}
</div>

<script>
    // 当网页向下滑动 20px 出现"返回顶部" 按钮
    window.onscroll = function () {
        scrollFunction()
    };

    function scrollFunction() {
        console.log(121);
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            document.getElementById("btnTop").style.display = "block";
        } else {
            document.getElementById("btnTop").style.display = "none";
        }
    }

    // 点击按钮，返回顶部
    function returnTop() {
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }
</script>
<div>
    <button onclick="returnTop()" id="btnTop" title="返回顶部">返回顶部</button>
</div>

</body>
</html>