models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models import Model
from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    last_active_time = Column(Integer, nullable=False, default=time.time)
    last_edit_time = Column(Integer, nullable=False, default=time.time)
    board_id = Column(Integer, nullable=False)
    reps = Column(Integer, nullable=False, default=0)
    last_rep_ = Column(Integer, nullable=False, default=-1)

    @classmethod
    def add(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        if m is not None:
            m.views += 1
            m.save()
            return m

    def last_reply(self):
        r = Reply.newest_n(1, topic_id=self.id)
        for rep in r:
            return rep

    @classmethod
    def delete(cls, t):
        replies = Reply.all(topic_id=t.id)
        deleted_rep_id_list = []
        for r in replies:
            r_id = r.id
            db.session.delete(r)
            deleted_rep_id_list.append(r_id)

        db.session.delete(t)
        db.session.commit()
        return deleted_rep_id_list

routes/mail.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    flash, abort, )

from models.message import Messages
from models.user import User
from routes import (login_required,
                    current_user,
                    cached_user_id2user,
                    new_csrf_token,
                    csrf_required,
                    )
from routes.myredis import (cached_sent_message,
                            data_cache,
                            cached_received_message,)

main = Blueprint('mail', __name__)


@main.app_template_filter()
def get_sender(message):
    """获取某条私信的发件人"""
    sender_id = message.sender_id
    return cached_user_id2user(sender_id)


@main.app_template_filter()
def get_receiver(k):
    """获取某条私信的收件人"""
    receiver_id = k.receiver_id
    return cached_user_id2user(receiver_id)


@main.app_template_global()
def unread_message_num_of_user(u):
    """获取未读私信条数"""
    if u is not None:
        uid = u.id
        all_messages = cached_received_message(uid)
        unread_messages = [m for m in all_messages if not m.been_read]
        n = len(unread_messages)
        if n > 0:
            return '[%d]' % n
    return ''


@main.route('/set_read', methods=['POST'])
@login_required
def set_read():
    """标记所有未读私信为已读"""
    u = current_user()
    receiver_id = int(request.form.get('receiver_id', -1))
    receiver = cached_user_id2user(receiver_id)
    if receiver is not None:
        if receiver_id == u.id:
            unread_messages = Messages.all(receiver_id=receiver_id, been_read=False)

            with data_cache.pipeline(transaction=False) as pipe:
                for message in unread_messages:
                    key = 'message_id_{}.message'.format(message.id)
                    message.been_read = True
                    message.save()
                    pipe.delete(key)
                pipe.execute()

    return redirect(url_for('.inbox'))


@main.route("/deliver", methods=["POST"])
@login_required
@csrf_required
def add():
    """发送新私信"""
    form = request.form.to_dict()
    u = current_user()
    receiver_id = form.get('receiver_id', None)

    if receiver_id is None:
        r_name = form.get('receiver_name', None)
        receiver = User.one(username=r_name)
    else:
        # receiver = User.one(id=receiver_id)
        receiver = cached_user_id2user(receiver_id)
    if receiver is None:
        flash('收件人不存在')
    elif receiver.id == u.id or receiver.username == u.username:
        flash('私信是发给其他人的哦，请重新输入收件人')
    else:
        Messages.send(
            title=form['title'],
            content=form['content'],
            sender_id=u.id,
            receiver_id=receiver.id,
        )
        flash('发送成功')
        with data_cache.pipeline(transaction=False) as pipe:
            key = 'user_id_{}.sent_message'.format(u.id)
            key2 = 'user_id_{}.received_message'.format(receiver_id)
            pipe.delete(key)
            pipe.delete(key2)
            pipe.execute()
    return redirect(url_for('.index'))


@main.route('/')
@login_required
def index():
    u = current_user()
    token = new_csrf_token()

    recv = Messages.newest_n(3, receiver_id=u.id)
    t = render_template(
        'mail/index.html',
        user=u,
        token=token,
        received=recv,
    )
    return t


@main.route('/inbox')
@login_required
def inbox():
    u = current_user()
    # unread = list(Messages.all(receiver_id=u.id, been_read=False))
    # unread.sort(key=lambda x: x.created_time, reverse=True)
    #
    # been_read = list(Messages.all(receiver_id=u.id, been_read=True))
    # been_read.sort(key=lambda x: x.created_time, reverse=True)
    all_messages = cached_received_message(u.id)

    unread = [m for m in all_messages if not m.been_read]
    been_read = [m for m in all_messages if m.been_read]

    return render_template('mail/inbox.html',
                           user=u,
                           unread=unread,
                           been_read=been_read
                           )


@main.route('/sent_box')
def sent_box():
    u = current_user()
    # sent_mails = list(Messages.all(sender_id=u.id))
    sent_mails = cached_sent_message(u.id)
    # sent_mails.sort(key=lambda x: x.created_time, reverse=True)
    return render_template('mail/sent_box.html',
                           user=u,
                           sent=sent_mails,
                           )


@main.route('/<int:id>')
@login_required
def view(id):
    message: Messages = Messages.one(id=id)
    u = current_user()
    is_sender = u.id == message.sender_id
    is_receiver = u.id == message.receiver_id
    if is_receiver or is_sender:

        if is_receiver and not message.been_read:
            message.been_read = True
            message.save()
            key = 'message_id_{}.message'.format(message.id)
            data_cache.delete(key)

        return render_template('mail/detail.html', message=message, user=u)
    else:
        return abort(404)


@main.route('/reply_page')
@login_required
def send_back():
    """用于回复私信"""
    receiver_id = request.args.get('receiver_id')
    token = new_csrf_token()
    u = current_user()
    receiver = cached_user_id2user(receiver_id)
    return render_template('mail/reply_page.html', user=u, token=token, receiver=receiver)

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
    flash,
    abort, )

from config import web_domain_name
from models.info import Info
from models.topic import Topic
from routes import (reply_owner_required_post,
                    current_user,
                    csrf_required,
                    login_required,
                    inform_at,
                    cached_topic_id2topic,
                    cached_reply_id2reply,
                    )

from models.reply import Reply
from routes.myredis import data_cache

main = Blueprint('my_reply', __name__)


@main.route('', methods=['POST'])
@login_required
@csrf_required
def add():
    form = request.form.to_dict()
    author = current_user()
    author_id = author.id
    form['user_id'] = author_id
    new_rep = Reply.new(form)

    # 有新的回复时，更新帖子的last_active_time
    t: Topic = Topic.one(id=new_rep.topic_id)
    t.last_active_time = new_rep.created_time
    t.last_rep_uid = author_id
    t.reps = t.reps + 1
    t.save()

    with data_cache.pipeline(transaction=False) as pipe:
        key = 'topic_id_{}.replies'.format(t.id)
        key2 = 'topic_id_{}.topic_info'.format(t.id)
        pipe.delete(key)
        pipe.delete(key2)
        pipe.execute()

    inform_at(t, new_rep.content, author)
    if author.id != t.user_id:
        # 如果是回复他人的帖子，则对主题主人发系统信息通知
        Info.send(title='{}刚刚回复了您的主题'.format(author.username),
                  receiver_id=t.user_id,
                  content='{}在您的主题{} 中发表了一个新回复,查看：\n\r{}/topic/{}'
                  .format(author.username, t.title, web_domain_name, t.id))
        key = 'user_id_{}.received_info'.format(t.user_id)
        data_cache.delete(key)

    return redirect(url_for('my_topic.detail', topic_id=new_rep.topic_id))


@main.route('/deletion', methods=['POST'])
@reply_owner_required_post
@csrf_required
# 先验证token, 再验证权限（是帖主或回复人）
def delete():
    i = int(request.form.get('reply_id', -1))
    rep: Reply = Reply.one(id=i)
    if rep is None:
        return abort(404)
    topic: Topic = Topic.one(id=rep.topic_id)
    Reply.delete(rep)
    with data_cache.pipeline(transaction=False) as pipe:
        key = 'topic_id_{}.replies'.format(topic.id)
        key2 = 'topic_id_{}.topic_info'.format(topic.id)
        pipe.delete(key)
        pipe.delete(key2)
        pipe.execute()

    # 更新帖子的last_active_time
    last_rep = topic.last_reply()
    topic.last_active_time = last_rep.created_time if last_rep is not None else topic.created_time
    topic.reps = topic.reps - 1
    topic.save()

    flash('回复删除成功')
    return redirect(url_for('my_topic.detail', topic_id=topic.id))

routes/topic.py
import time

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    flash,
    abort,
)

from sqlalchemy import desc
from models.base_model import db
from models.board import Board
from routes import (current_user,
                    csrf_required,
                    new_csrf_token,
                    login_required,
                    inform_at,
                    topic_owner_required_post,
                    at_users,
                    cached_topic_id2topic,
                    )

from models.topic import Topic
from routes.myredis import (data_cache,
                            cached_replies_by_topic_id,
                            cached_user_id2user,
                            )

main = Blueprint('my_topic', __name__)


@main.app_template_filter()
def get_author(topic):
    """获取话题作者"""
    author_id = topic.user_id
    return cached_user_id2user(author_id)


@main.app_template_filter()
def content_with_clickable_name(content: str):
    """@功能"""
    for n in at_users(content):
        s = '@' + n.username
        content = content.replace(s, '<a href="/user/{}">@{}</a>'.format(n.id, n.username))
    return content


@main.route('/')
def index():
    """获取话题主页，每个话题cell 最后回复人的头像，
    最后变动时间，作者头像，评论数、浏览数。
    根据query选定板块"""
    visitor = current_user()
    board_id = int(request.args.get('board_id', -1))
    current_bid = board_id
    if board_id == -1:
        recent_active_topics = db.session.query(Topic).order_by(desc(Topic.last_active_time))
    else:
        recent_active_topics = db.session.query(Topic).filter_by(board_id=current_bid).order_by(
            desc(Topic.last_active_time))
    bs = Board.all()
    return render_template('topic/index.html',
                           recent_topics=recent_active_topics,
                           current_bid=current_bid,
                           user=visitor,
                           bs=bs,
                           )


@main.route('/<topic_id>')
def detail(topic_id):
    """
    id 为Topic 的话题的详情页
    """
    cur_topic = Topic.get(topic_id)
    if cur_topic is None:
        return abort(404)

    key = 'topic_id_{}.topic_info'.format(topic_id)
    # 每次有人点开详情页，需要更新浏览数，故旧缓存作废
    data_cache.delete(key)
    replies = cached_replies_by_topic_id(topic_id)
    board = Board.one(id=cur_topic.board_id)
    author = cached_user_id2user(cur_topic.user_id)
    token = new_csrf_token()
    return render_template('topic/detail.html',
                           topic=cur_topic,
                           replies=replies,
                           author=author,
                           token=token,
                           board=board,
                           visitor=current_user()
                           )


@main.route('', methods=['POST'])
@login_required
@csrf_required
def add():
    """
    执行新增Topic
    """
    form = request.form.to_dict()
    u = current_user()
    t = Topic.add(form, user_id=u.id)

    # 新增话题后，user_id 下所有话题的缓存失效，清理旧缓存。
    key = 'user_id_{}.created_topics'.format(u.id)
    data_cache.delete(key)

    inform_at(t, t.content, u)
    return redirect(url_for('.detail', topic_id=t.id))


@main.route("/posting")
@login_required
def new():
    """进入新建Topic的编辑页面"""
    current_bid = int(request.args.get('board_id', -1))
    token = new_csrf_token()
    u = current_user()
    bs = Board.all()
    return render_template("topic/new.html",
                           token=token,
                           user=u,
                           current_bid=current_bid,
                           bs=bs
                           )


@main.route("/deletion", methods=['POST'])
@topic_owner_required_post
@csrf_required
def delete():
    """删除某个话题，话题id从form中获取"""
    user_id = current_user().id
    i = int(request.form.get('topic_id', -1))
    topic = Topic.one(id=i)
    if topic is not None:
        # 删帖后，清理该帖子相关的缓存
        with data_cache.pipeline(transaction=False) as pipe:
            key = 'topic_id_{}.topic_info'.format(i)
            key2 = 'user_id_{}.created_topics'.format(user_id)
            key3 = 'topic_id_{}.replies'.format(topic.id)
            pipe.delete(key)
            pipe.delete(key2)
            pipe.delete(key3)

            delete_rep_id_list = Topic.delete(topic)
            for i in delete_rep_id_list:
                key = 'reply_id_{}.reply_info'.format(i)
                data_cache.delete(key)
            pipe.execute()

        flash('帖子删除成功')
    return redirect(url_for('my_user.user_created_topics', user_id=user_id))


@main.route("/<topic_id>/edit")
@login_required
def edit(topic_id):
    """进入话题编辑页面的get请求"""
    # old_topic: Topic = Topic.one(id=id)
    old_topic: Topic = cached_topic_id2topic(topic_id)
    token = new_csrf_token()
    u = current_user()
    all_borads = Board.all()

    if u.id != old_topic.user_id:
        return abort(404)

    return render_template("topic/edit.html",
                           token=token,
                           user=u,
                           current_bid=old_topic.board_id,
                           bs=all_borads,
                           old_topic=old_topic,
                           )


@main.route("/<int:id>/edit", methods=['POST'])
@login_required
@csrf_required
# 从编辑页面提交修改的post请求
def edit_post(id):
    form = request.form.to_dict()
    now = time.time()
    Topic.update(id, **form, last_edit_time=now, last_active_time=now)
    key = 'topic_id_{}.topic_info'.format(id)
    data_cache.delete(key)
    return redirect(url_for('.detail', topic_id=id))

templates/topic/detail.html
{% extends "base_nav.html" %}
{% block title %}查看话题 - {{ topic.title }}{% endblock %}

{% block main %}
    <div id="sidebar">
        <div class="panel">

            <div class="header">
                <span class="col_fade">作者信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="/user/{{ author.id }}">
                            <img alt="用户头像" src="{{ author.image }}" title="{{ author.username }}">
                        </a>
                        <span class="user_name"><a class="dark"
                                                   href="/user/{{ author.id }}">{{ author.username }}</a></span>

                        <div class="space clearfix"></div>
                        <span class="signature">
        {{ author.signature }}
    </span>
                        {% if visitor.id != author.id %}
                            <div class="space clearfix"></div>
                            <a href="{{ url_for('mail.send_back',receiver_id=author.id) }}" id="create_topic_btn">
                                <span class="span-success">私信</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>


        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('my_topic.new',  token=token) }}" id="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">友情链接</span>
            </div>
            <div class="inner">
                <ol class="friendship-community">
                    <li>
                        <a href="https://www.python.org/" target="_blank">
                            <img src="/images/python-logo.png">
                        </a>
                    </li>
                    <div class="sep10"></div>
                </ol>
            </div>
        </div>


        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>本站作者</span>
            </div>
            <div class='inner cnode-app-download'>
                <img width='200' src="/images/my_weixin.png">
                <br/>
                扫一扫添加Swordman
                <br>
                <a href="https://github.com/imjerry1994/web_bbs">本站源码</a>
            </div>
        </div>
    </div>
    <div id="content">
        <p class="controls" style="color:#a9302a">{{ get_flashed_messages()[0] }}</p>
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 {{ topic.created_time | format_time }}
            </span>
                    <span>
                        {% set u = topic | get_author %}
                作者 <a href="/user/{{ u.id }}">{{ u.username }}</a>
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 <a href="{{ url_for(".index", board_id=board.id) }}">{{ board.title }}</a>
            </span>
                </div>
            </div>
            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content | content_with_clickable_name }}</div>
                </div>


            </div>
            <div class="cell">
                <div class="changes">
                    <span>
                        最后修改于 {{ topic.last_edit_time | format_time }}
                    </span>
                </div>
                {% if visitor.id == author.id %}
                    <form id='reply_form' action="{{ url_for('my_topic.delete',token=token) }}" method="post">
                        <input type="hidden" name="topic_id" value="{{ topic.id }}">

                        <div class='editor_buttons'>
                            <input class='span-primary submit_btn' type="submit" style="background-color: #da4f49"
                                   value="删除话题">
                        </div>
                    </form>

                    <form id='reply_form' action="{{ url_for('my_topic.edit',topic_id=topic.id) }}" method="get">
                        <div class='editor_buttons'>
                            <input class='span-primary submit_btn' type="submit" style="background-color: #da4f49"
                                   value="编辑话题">
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>


        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>
                    {{ replies | count }} 回复
                </span>
            </div>
            {% for r in replies %}
                {% set rep_user = r.user() %}
                <div class='cell reply_area reply_item'>
                    <div class='user_info'>
                        <a class="user_avatar" href="/user/{{ rep_user.id }}">
                            <img alt="用户头像" src="{{ rep_user.image }}" title="{{ rep_user.username }}">
                        </a>
                        <a class='dark reply_author'>
                            <a href="/user/{{ rep_user.id }}">{{ rep_user.username }}</a>
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}/{{ loop.length }} 楼 •
                            <span>{{ r.created_time | format_time }}</span>
                        </a>
                    </div>
                    <div class='user_action'>
                        {% if visitor.id == r.user_id or visitor.id == topic.user_id %}
                            <form id='reply_form' action="{{ url_for('my_reply.delete',token=token) }}"
                                  method="post">
                                <input type="hidden" name="reply_id" value="{{ r.id }}">

                                <div class='editor_buttons'>
                                    <input class='span-primary submit_btn' type="submit"
                                           style="background-color: #da4f49"
                                           value="删除评论">
                                </div>
                            </form>
                        {% endif %}
                        <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                    </div>
                    <div class='reply_content from-leiwei1991'>
                        <div class="markdown-text">{{ r.content | content_with_clickable_name }}</div>
                    </div>

                </div>
            {% endfor %}
        </div>

        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>添加回复</span>
            </div>

            <div class='inner reply'>
                <form id='reply_form' action="{{ url_for('my_reply.add',token=token) }}" method="post">
                    <input type="hidden" name="topic_id" value="{{ topic.id }}">

                    <textarea class='editor' name="content" rows='8' required></textarea>

                    <div class='editor_buttons'>
                        <input class='span-primary submit_btn' type="submit" data-loading-text="回复中.." value="回复">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="//cdn.bootcss.com/prism/1.8.0/themes/prism.css" rel="stylesheet">
    <script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
    <script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
    <script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
    <script>
        var e = function (sel) {
            return document.querySelector(sel)
        }

        var es = function (sel) {
            return document.querySelectorAll(sel)
        }

        var markContents = function () {
            // markdown -> html 的处理放在高亮前面
            // 因为高亮是针对 html 格式的
            // lang -> language 不需要转 prism 自动转了
            var contentDivs = es('.markdown-text')
            for (var i = 0; i < contentDivs.length; i++) {
                var contentDiv = contentDivs[i]
                console.log('pre marked', contentDiv.textContent)
                var content = marked(contentDiv.textContent)
                console.log('after marked', content)
                contentDiv.innerHTML = content
            }
        }

        var highlight = function () {
            // 自动加载对应的语言 不然要手动加入各个语言的 js
            Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
        }

        var __main = function () {
            markContents()
            highlight()
        }

        __main()

    </script>
{% endblock %}

templates/topic/edit.html
{% extends "base.html" %}
{% block title %}编辑话题  {{ old_topic.title }}{% endblock %}
{% block main %}
    <div id="content">
        <div class="header">
            <ul class="breadcrumb">
                <li><a href="/">主页</a><span class="divider">/</span></li>
                <li class='active'>编辑话题</li>
            </ul>
        </div>
        <br>
        <div class="panel">
            <div class="inner post">
                <form id="create_topic_form" method="post"
                      action="{{ url_for('my_topic.edit',topic_id=old_topic.id,token=token) }}">
                    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上" required>{{ old_topic.title }}</textarea>
                        <div class='markdown_editor in_editor'>
                            <span class="tab-selector">投递版块：</span>

                            <select name="board_id" id="board" required>
                                {% for b in bs %}
                                    {% if b.id == current_bid %}
                                        <option value="{{ b.id }}" selected>{{ b.title }}</option>
                                    {% else %}
                                        <option value="{{ b.id }}">{{ b.title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>

                            <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20'
                                          placeholder='文章支持 Markdown 语法, 请注意标记代码'
                                          required>{{ old_topic.content }}</textarea>
                                <div class='editor_buttons'>
                                    <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                           value="提交编辑">
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/topic/index.html
{% extends "base_nav.html" %}
{% block title %}话题广场{% endblock %}
{% block main %}
    <!-- sidebar -->
    <div id="sidebar">
        {% if user %}
            <div class="panel">

                <div class="header">
                    <span class="col_fade">个人信息</span>
                </div>
                <div class="inner">
                    <div class="user_card">
                        <div>
                            <a class="user_avatar" href="/user/{{ user.id }}">
                                <img alt="用户头像" src="{{ user.image }}" title="{{ user.username }}">
                            </a>
                            <span class="user_name"><a class="dark"
                                                       href="/user/{{ user.id }}">{{ user.username }}</a></span>

                            <div class="space clearfix"></div>
                            <span class="signature">
        {{ user.signature }}
    </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel">
                <div class="inner">
                    <a href="{{ url_for('my_topic.new', board_id=current_bid) }}"
                       id="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
        {% endif %}
        <div class="panel">
            <div class="header">
                <span class="col_fade">友情链接</span>
            </div>
            <div class="inner">
                <ol class="friendship-community">
                    <li>
                        <a href="https://www.python.org/" target="_blank">
                            <img src="/images/python-logo.png">
                        </a>
                    </li>
                    <div class="sep10"></div>
                </ol>
            </div>
        </div>

        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>本站作者</span>
            </div>
            <div class='inner cnode-app-download'>
                <img width='200' src="/images/my_weixin.png">
                <br/>
                扫一扫添加Swordman
                <br>
                <a href="https://github.com/imjerry1994/web_bbs">本站源码</a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                {% if current_bid == -1 %}
                    <a href="/topic"
                       class="topic-tab current-tab">全部</a>
                {% else %}
                    <a href="/topic"
                       class="topic-tab">全部</a>
                {% endif %}

                {% for b in bs %}
                    {% if b.id == current_bid %}
                        <a href="/topic?board_id={{ b.id }}"
                           class="topic-tab current-tab">{{ b.title }}</a>
                    {% else %}
                        <a href="/topic?board_id={{ b.id }}"
                           class="topic-tab">{{ b.title }}</a>
                    {% endif %}
                {% endfor %}

            </div>

            <div class="inner no-padding">
                <div id="topic_list">
                    {% for topic in recent_topics %}
                        <div class="cell">
                            {% set author = topic | get_author %}
                            <a class="user_avatar pull-left" href="/user/{{ author.id }}">
                                <img alt="用户头像" src="{{ author.image }}" title="{{ author.username }}">
                            </a>
                            <span class="reply_count pull-left">
                    <span class="count_of_replies" title="回复数">
                      {{ topic.reps }}
                    </span>
                    <span class="count_seperator">/</span>
                    <span class="count_of_visits" title="点击数">{{ topic.views }}</span>
                      </span>


                            <a class="last_time pull-right" href="/topic/{{ topic.id }}">
                                {% set rep = topic.last_reply() %}
                                {% if rep %}
                                    {% set rep_author = rep | get_author %}
                                    <img class="user_small_avatar" alt="用户头像" src="{{ rep_author.image }}">
                                {% endif %}
                                <span class="last_active_time">{{ topic.last_active_time | how_long_ago }}</span>
                            </a>

                            <div class="topic_title_wrapper">

                                <a class="topic_title" href="/topic/{{ topic.id }}" title="{{ topic.title }}">
                                    {{ topic.title }}
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}