models/user.py
from flask import flash
from sqlalchemy import Column, String

import config
from models.base_model import SQLMixin, db


class User(SQLMixin, db.Model):
    """
    User 是一个保存用户数据的 model
     用户名 和 用户密码
     用户头像uri 和 用户邮箱
    """
    username = Column(String(50), nullable=False)
    password = Column(String(256), nullable=False)
    image = Column(String(100), nullable=False, default='/images/default_profile.jpg')
    email = Column(String(50), nullable=False, default=config.test_mail)
    signature = Column(String(256), nullable=False, default='该用户太懒,什么也没有写。')

    @classmethod
    def salted_password(cls, password, salt='$!@><?>HUI&DWQa`'):
        import hashlib

        def sha256(ascii_str):
            return hashlib.sha256(ascii_str.encode('ascii')).hexdigest()

        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        print('sha256', len(hash2))
        return hash2

    def hashed_password(self, pwd):
        import hashlib
        # 用 ascii 编码转换成 bytes 对象
        p = pwd.encode('ascii')
        s = hashlib.sha256(p)
        # 返回摘要字符串
        return s.hexdigest()

    @classmethod
    def register(cls, form):
        name = form['username']
        password = form['password']
        email = form['email']
        if User.one(email=email) is not None or User.one(username=name) is not None:
            flash('用户名被占用，请重新输入')
            return None

        if len(name) > 0 and len(password) > 2:
            u = User.new(form)
            u.password = u.salted_password(password)
            u.save()
            return u

    @classmethod
    def validate_login(cls, form):
        user = User.one(username=form['username'])
        if user is not None and user.password == User.salted_password(form['password']):
            return user
        else:
            return None

routes/topic.py
import time

from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    flash,
    abort,
)

from sqlalchemy import desc
from models.base_model import db
from models.board import Board
from routes import (current_user,
                    csrf_required,
                    new_csrf_token,
                    login_required,
                    inform_at,
                    topic_owner_required_post,
                    at_users,
                    cached_topic_id2topic,
                    )

from models.topic import Topic
from routes.myredis import (data_cache,
                            cached_replies_by_topic_id,
                            cached_user_id2user,
                            )

main = Blueprint('my_topic', __name__)


@main.app_template_filter()
def get_author(topic):
    """获取话题作者"""
    author_id = topic.user_id
    return cached_user_id2user(author_id)


@main.app_template_filter()
def content_with_clickable_name(content: str):
    """@功能"""
    for n in at_users(content):
        s = '@' + n.username
        content = content.replace(s, '<a href="/user/{}">@{}</a>'.format(n.id, n.username))
    return content


@main.route('/')
def index():
    """获取话题主页，每个话题cell 最后回复人的头像，
    最后变动时间，作者头像，评论数、浏览数。
    根据query选定板块"""
    visitor = current_user()
    board_id = int(request.args.get('board_id', -1))
    current_bid = board_id
    if board_id == -1:
        recent_active_topics = db.session.query(Topic).order_by(desc(Topic.last_active_time))
    else:
        recent_active_topics = db.session.query(Topic).filter_by(board_id=current_bid).order_by(
            desc(Topic.last_active_time))
    bs = Board.all()
    return render_template('topic/index.html',
                           recent_topics=recent_active_topics,
                           current_bid=current_bid,
                           user=visitor,
                           bs=bs,
                           )


@main.route('/<topic_id>')
def detail(topic_id):
    """
    id 为Topic 的话题的详情页
    """
    cur_topic = Topic.get(topic_id)
    if cur_topic is None:
        return abort(404)

    key = 'topic_id_{}.topic_info'.format(topic_id)
    # 每次有人点开详情页，需要更新浏览数，故旧缓存作废
    data_cache.delete(key)
    replies = cached_replies_by_topic_id(topic_id)
    board = Board.one(id=cur_topic.board_id)
    author = cached_user_id2user(cur_topic.user_id)
    token = new_csrf_token()
    return render_template('topic/detail.html',
                           topic=cur_topic,
                           replies=replies,
                           author=author,
                           token=token,
                           board=board,
                           visitor=current_user()
                           )


@main.route('', methods=['POST'])
@login_required
@csrf_required
def add():
    """
    执行新增Topic
    """
    form = request.form.to_dict()
    u = current_user()
    t = Topic.add(form, user_id=u.id)

    # 新增话题后，user_id 下所有话题的缓存失效，清理旧缓存。
    key = 'user_id_{}.created_topics'.format(u.id)
    data_cache.delete(key)

    inform_at(t, t.content, u)
    return redirect(url_for('.detail', topic_id=t.id))


@main.route("/posting")
@login_required
def new():
    """进入新建Topic的编辑页面"""
    current_bid = int(request.args.get('board_id', -1))
    token = new_csrf_token()
    u = current_user()
    bs = Board.all()
    return render_template("topic/new.html",
                           token=token,
                           user=u,
                           current_bid=current_bid,
                           bs=bs
                           )


@main.route("/deletion", methods=['POST'])
@topic_owner_required_post
@csrf_required
def delete():
    """删除某个话题，话题id从form中获取"""
    user_id = current_user().id
    i = int(request.form.get('topic_id', -1))
    topic = Topic.one(id=i)
    if topic is not None:
        # 删帖后，清理该帖子相关的缓存
        with data_cache.pipeline(transaction=False) as pipe:
            key = 'topic_id_{}.topic_info'.format(i)
            key2 = 'user_id_{}.created_topics'.format(user_id)
            key3 = 'topic_id_{}.replies'.format(topic.id)
            pipe.delete(key)
            pipe.delete(key2)
            pipe.delete(key3)

            delete_rep_id_list = Topic.delete(topic)
            for i in delete_rep_id_list:
                key = 'reply_id_{}.reply_info'.format(i)
                data_cache.delete(key)
            pipe.execute()

        flash('帖子删除成功')
    return redirect(url_for('my_user.user_created_topics', user_id=user_id))


@main.route("/<topic_id>/edit")
@login_required
def edit(topic_id):
    """进入话题编辑页面的get请求"""
    # old_topic: Topic = Topic.one(id=id)
    old_topic: Topic = cached_topic_id2topic(topic_id)
    token = new_csrf_token()
    u = current_user()
    all_borads = Board.all()

    if u.id != old_topic.user_id:
        return abort(404)

    return render_template("topic/edit.html",
                           token=token,
                           user=u,
                           current_bid=old_topic.board_id,
                           bs=all_borads,
                           old_topic=old_topic,
                           )


@main.route("/<int:id>/edit", methods=['POST'])
@login_required
@csrf_required
# 从编辑页面提交修改的post请求
def edit_post(id):
    form = request.form.to_dict()
    now = time.time()
    Topic.update(id, **form, last_edit_time=now, last_active_time=now)
    key = 'topic_id_{}.topic_info'.format(id)
    data_cache.delete(key)
    return redirect(url_for('.detail', topic_id=id))

routes/user.py
import os
import uuid

from flask import (render_template,
                   abort,
                   request,
                   flash,
                   redirect,
                   url_for,
                   send_from_directory,
                   Blueprint,
                   )

from werkzeug.datastructures import FileStorage

from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import (login_required,
                    current_user,
                    new_csrf_token,
                    csrf_required,
                    cached_topic_id2topic,
                    cached_user_id2user,
                    )
from routes.myredis import (cached_created_topics,
                            cached_replied_topics,
                            data_cache,
                            )

main = Blueprint('my_user', __name__)


@main.route('/profile')
@login_required
def profile():
    """用户的个人主页"""
    u = current_user()
    visitor_id = u.id
    recent_create_topics = Topic.newest_n(5, user_id=visitor_id)
    replies = Reply.newest_n(user_id=visitor_id)
    recent_rep_topics = []
    for rep in replies:
        topic = cached_topic_id2topic(rep.topic_id)
        if topic not in recent_rep_topics:
            recent_rep_topics.append(topic)
        if len(recent_rep_topics) >= 5:
            break

    return render_template('user/user_profile.html',
                           user=u,
                           recent_rep_topics=recent_rep_topics,
                           recent_create_topics=recent_create_topics,
                           visitor_id=visitor_id)


@main.route('/user/<user_id>')
def user_detail(user_id):
    """访问其他用户"""
    u = cached_user_id2user(user_id)
    visitor = current_user()
    if u is None:
        return abort(404)
    else:
        recent_create_topics = Topic.newest_n(5, user_id=user_id)
        replies = Reply.newest_n(user_id=user_id)
        recent_rep_topics = []
        for rep in replies:
            topic = cached_topic_id2topic(rep.topic_id)
            if topic not in recent_rep_topics:
                recent_rep_topics.append(topic)
            if len(recent_rep_topics) >= 5:
                break

        return render_template('user/user_profile.html',
                               user=u,
                               visitor=visitor,
                               recent_rep_topics=recent_rep_topics,
                               recent_create_topics=recent_create_topics,
                               )


@main.route('/user/<user_id>/topics/')
def user_created_topics(user_id):
    """查看用户发表的所有帖子"""
    u = cached_user_id2user(user_id)
    if u is None:
        abort(404)
    else:
        topics = cached_created_topics(user_id)
        topics.sort(key=lambda x: x.last_active_time, reverse=True)
        return render_template('user/user_items.html',
                               itemtype='创建',
                               topics=topics,
                               user=u,
                               )


@main.route('/user/<user_id>/replies/')
def user_replied_topics(user_id):
    """查看用户回复过的所有帖子"""
    u = cached_user_id2user(user_id)
    if u is None:
        abort(404)
    else:
        # replies = Reply.all(user_id=id)
        #
        # topics = []
        # if replies:
        #     for rep in replies:
        #         topic = Topic.one(id=rep.topic_id)
        #         if topic not in topics:
        #             topics.append(topic)
        #     topics.sort(key=lambda x: x.last_active_time, reverse=True)
        topics = cached_replied_topics(user_id)
        return render_template('user/user_items.html',
                               itemtype='参与',
                               topics=topics,
                               user=u,
                               )


@main.route('/setting')
@login_required
def setting():
    """设置页面"""
    u = current_user()
    token = new_csrf_token()
    return render_template('user/setting.html', user=u, token=token)


@main.route('/setting', methods=['POST'])
@login_required
@csrf_required
def setting_post():
    """提交更改"""
    u = current_user()
    form = request.form.to_dict()

    if form['action'] == 'change_password':  # 如果用户点击的是更改密码
        new_pass = form['new_pass']

        if u.password == User.salted_password(form['old_pass']):
            if len(new_pass) <= 2:
                flash('密码强度过低，请重新输入')
            else:
                User.update(u.id, password=User.salted_password(new_pass))
                key = 'user_id_{}.user_info'.format(u.id)
                data_cache.delete(key)
                flash('密码修改成功')
        else:
            flash('密码错误，请重新输入')

    elif form['action'] == 'change_settings':
        # 如果用户点击的是更改设置，修改同步到数据库，并清理redis失效缓存
        new_name = form['name']
        if new_name != u.username:  # 如果修改了用户名，需要检测新用户名是否被占用
            if User.one(username=new_name) is None:
                User.update(u.id, username=new_name, signature=form['signature'])
                key = 'user_id_{}.user_info'.format(u.id)
                data_cache.delete(key)
                flash('个人资料修改成功')
            else:
                flash('用户名被占用，请重新输入')
        else:  # 如果没修改用户名
            User.update(u.id, signature=form['signature'])
            key = 'user_id_{}.user_info'.format(u.id)
            data_cache.delete(key)
            flash('个人资料修改成功')

    return redirect(url_for('.setting'))


@main.route('/image/avatar', methods=['POST'])
@login_required
@csrf_required
def avatar_set():
    """设置头像"""
    u = current_user()
    file: FileStorage = request.files['avatar']
    filename = 'avatar_uid=[{}]'.format(u.id)+str(uuid.uuid4())
    path = os.path.join('images', filename)
    file.save(path)
    User.update(u.id, image='/images/{}'.format(filename))
    key = 'user_id_{}.user_info'.format(u.id)
    data_cache.delete(key)
    return redirect(url_for('.profile'))


@main.route('/images/<filename>')
def image(filename):
    return send_from_directory('images', filename)

templates/user/setting.html
{% extends "base.html" %}
{% block title %}个人设置{% endblock %}
{% block main %}
    <div id="content">
    <div class="controls" style="color:#a9302a">{{ get_flashed_messages()[0] }}</div>
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="/">主页</a><span class="divider">/</span></li>
                    <li class='active'>设置</li>
                </ul>

            </div>
        </div>
            <div class='panel'>
                <div class="header"><span class='col_fade'>个人资料</span></div>
            <div class='inner'>

                <form id='setting_form' class='form-horizontal'
                      action='{{url_for('my_user.setting_post', token=token) }}' method='post'>

                    <div class='control-group'>
                        <label class='control-label' for='name'>用户名</label>

                        <div class='controls'>
                            <input class='input-xlarge' id='name' name='name' size='30' type='text'
                                   value="{{ user.username }}" required/>
                        </div>
                    </div>

                    <div class='control-group'>
                        <label class='control-label' for='signature'>个性签名</label>

                        <div class='controls'>
                            <textarea class='input-xlarge' id='signature' name='signature' size='30'
                                      placeholder="请输入新签名" required>{{ user.signature }}</textarea>
                        </div>
                    </div>
                    <input type='hidden' id='action' name='action' value='change_settings'/>
                    <div class='form-actions'>
                        <input type='submit' class='span-primary submit_btn' required data-loading-text="保存中.." value='保存设置'/>
                    </div>

                </form>

            </div>
{#        </div>#}


{#        <div class='panel'>#}
            <div class='header'>
                <span class='col_fade'>更改密码</span>
            </div>
            <div class='inner'>
                <form id='change_pass_form' class='form-horizontal' action='{{url_for('my_user.setting_post', token=token) }}' method='post'>
                    <div class='control-group'>
                        <label class='control-label' for='old_pass'>当前密码</label>

                        <div class='controls'>
                            <input class='input-xlarge' type='password' required id='old_pass' name='old_pass' size='30'/>
                        </div>
                    </div>

                    <div class='control-group'>
                        <label class='control-label' for='old_pass'>新密码</label>

                        <div class='controls'>
                            <input class='input-xlarge' type='password' required id='new_pass' name='new_pass' size='30'/>
                        </div>
                    </div>

                    <input type='hidden' id='action' name='action' value='change_password'/>


                    <div class='form-actions'>
                        <input type='submit' class='span-primary submit_btn' data-loading-text="提交中.." value='修改密码'/>
                    </div>
                </form>
            </div>
{#        </div>#}

{#        <div class='panel'>#}
            <div class='header'>
                <span class='col_fade'>更改头像</span>
            </div>
            <div class='inner'>

                <form method="post"
                      action="{{ url_for('my_user.avatar_set',token=token) }}"
                      enctype="multipart/form-data"
                class='form-horizontal'>
                        <div class='controls'>
                    <input type="file" class="input-xlarge" name="avatar" required>
                        </div>

                    <div class='form-actions'>
                        <input type='submit' class='span-primary submit_btn' data-loading-text="更改中.." value='上传头像'/>
                    </div>
                    <img class='controls' src="{{ user.image }}" width="20%">
                </form>

            </div>
        </div>
    </div>
{% endblock %}

templates/user/user_items.html
{% extends "base.html" %}
{% block title %}@{{ user.username }}的主页{% endblock %}
{% block main %}
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="/">主页</a><span class="divider">/</span></li>
                    <li><a href="/user/{{ user.id }}">{{ user.username }} 的主页</a></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img alt="用户头像" src="{{ user.image }}" class="user_avatar" title="{{ user.username }}">
                </div>
                <div class='user_profile'>
                </div>
                <p class="col_fade">用户注册时间 {{ user.created_time | how_long_ago }}</p>

            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">{{ user.username }} {{ itemtype }}的话题</span>
            </div>
            <div class="inner post">
                <p class="controls" style="color:#a9302a">{{ get_flashed_messages()[0] }}</p>
                {% if topics %}
                    <div class="topic_list">
                        {% for topic in topics %}
                            <div class="cell">

                                {% set author = topic | get_author %}
                                <a class="user_avatar pull-left" href="/user/{{ author.id }}">
                                    <img alt="用户头像" src="{{ author.image }}" title="{{ author.username }}">
                                </a>

                                <span class="reply_count pull-left">
    <span class="count_of_replies" title="回复数">
      {{ topic.reps }}
    </span>
    <span class="count_seperator">/</span>
    <span class="count_of_visits" title="点击数">
      {{ topic.views }}
    </span>
  </span>


                                <a class="last_time pull-right" href="/topic/{{ topic.id }}">
                                    {% set s = topic.last_reply() %}
                                    {% if s %}
                                        <img class="user_small_avatar" alt="用户头像" src="{{ (s | get_author).image }}">
                                    {% endif %}
                                    <span class="last_active_time">{{ topic.last_active_time | how_long_ago }}</span>
                                </a>

                                <div class="topic_title_wrapper">

                                    <a class="topic_title" href="/topic/{{ topic.id }}" title="{{ topic.title }}">
                                        {{ topic.title }}
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <a class="dark">不问世事，惜墨如金</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/user_profile.html
{% extends "base_nav.html" %}
{% block title %}@{{ user.username }} 的主页{% endblock %}
{% block main %}
    <div id="sidebar">
        <div class="panel">

            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="/user/{{ user.id }}">
                            <img alt="用户头像" src="{{ user.image }}" title="{{ user.username }}">
                        </a>
                        <span class="user_name"><a class="dark"
                                                   href="/user/{{ user.id }}">{{ user.username }}</a></span>

                        <div class="space clearfix"></div>
                        <span class="signature">
        {{ user.signature }}
    </span>
                        {% if visitor != user.id %}
                            <div class="space clearfix"></div>
                            <a href="/mail/sender/{{ user.id }}" id="create_topic_btn">
                                <span class="span-success">私信</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>


        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('my_topic.new') }}" id="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">友情链接</span>
            </div>
            <div class="inner">
                <ol class="friendship-community">
                    <li>
                        <a href="https://www.python.org/" target="_blank">
                            <img src="/images/python-logo.png">
                        </a>
                    </li>
                    <div class="sep10"></div>
                </ol>
            </div>
        </div>

        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>本站作者</span>
            </div>
            <div class='inner cnode-app-download'>
                <img width='200' src="/images/my_weixin.png">
                <br/>
                扫一扫添加Swordman
                <br>
                <a href="https://github.com/imjerry1994/web_bbs">本站源码</a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="/">主页</a><span class="divider">/</span></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img alt="用户头像" src="{{ user.image }}" class="user_avatar" title="{{ user.username }}">
                </div>
                <div class='user_profile'>
                </div>
                <p class="col_fade">用户注册时间 {{ user.created_time | how_long_ago }}</p>

            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>
            <div class="inner post">
                {% if recent_create_topics %}

                    {% for topic in recent_create_topics %}
                        <div class="cell">

                            {% set author = topic | get_author %}
                            <a class="user_avatar pull-left" href="/user/{{ author.id }}">
                                <img alt="用户头像" src="{{ author.image }}" title="{{ author.username }}">
                            </a>

                            <span class="reply_count pull-left">
    <span class="count_of_replies" title="回复数">
      {{ topic.reps }}
    </span>
    <span class="count_seperator">/</span>
    <span class="count_of_visits" title="点击数">
      {{ topic.views }}
    </span>
  </span>


                            <a class="last_time pull-right" href="/topic/{{ topic.id }}">
                                {% set s = topic.last_reply() %}
                                {% if s %}
                                    <img class="user_small_avatar" alt="用户头像" src="{{ s.user().image }}">
                                {% endif %}
                                <span class="last_active_time">{{ topic.last_active_time | how_long_ago }}</span>
                            </a>

                            <div class="topic_title_wrapper">

                                <a class="topic_title" href="/topic/{{ topic.id }}" title="{{ topic.title }}">
                                    {{ topic.title }}
                                </a>
                            </div>
                        </div>
                    {% endfor %}


                    <div class="cell more">
                        <a class="dark" href="/user/{{ user.id }}/topics">查看更多»</a>
                    </div>
                {% else %}
                    <a class="dark">惜墨如金</a>
                {% endif %}
            </div>

        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">最近参与的话题</span>
            </div>
            <div class="inner post">
                {% if recent_rep_topics %}
                    {% for topic in recent_rep_topics %}



                        <div class="cell">

                            {% set author = topic | get_author %}
                            <a class="user_avatar pull-left" href="/user/{{ author.id }}">
                                <img alt="用户头像" src="{{ author.image }}" title="{{ author.username }}">
                            </a>

                            <span class="reply_count pull-left">

    <span class="count_of_replies" title="回复数">
      {{ topic.reps }}
    </span>
    <span class="count_seperator">/</span>
    <span class="count_of_visits" title="点击数">{{ topic.views }}</span>
  </span>

                            <a class="last_time pull-right" href="/topic/{{ topic.id }}">
                                {% set s = topic.last_reply() %}
                                {% if s %}
                                    <img class="user_small_avatar" alt="用户头像" src="{{ s.user().image }}">
                                {% endif %}
                                <span class="last_active_time">{{ topic.last_active_time | how_long_ago }}</span>
                            </a>


                            <div class="topic_title_wrapper">

                                <a class="topic_title" href="/topic/{{ topic.id }}" title="{{ topic.title }}">
                                    {{ topic.title }}
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="cell more">
                        <a class="dark" href="/user/{{ user.id }}/replies">查看更多»</a>
                    </div>
                {% else %}
                    <a class="dark">不问世事</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}